pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "status-success=build (humble)"
      - "label=bot"
    actions:
      merge:
        method: merge
        allow_merging_configuration_change: true
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
