controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    usv_joy_controller:
      type: usv_controller/UsvJoyController
    usv_velocity_controller:
      type: usv_controller/UsvVelocityController

usv_joy_controller:
  ros__parameters:
    left_thruster_joint: left_chasis_engine_joint
    right_thruster_joint: right_chasis_engine_joint
    left_azimuth_joint: left_engine_propeller_joint
    right_azimuth_joint: right_engine_propeller_joint
    joy_topic : /joy

usv_velocity_controller:
  ros__parameters:
    left_thruster_joint: left_chasis_engine_joint
    right_thruster_joint: right_chasis_engine_joint
    left_azimuth_joint: left_engine_propeller_joint
    right_azimuth_joint: right_engine_propeller_joint
    linear_pid_gain:
      kp: 10.0
      ki: 0.0
      kd: 0.01
      i_min: -100.0
      i_max: 100.0
      antiwindup: true
    anguler_pid_gain:
      kp: 0.1
      ki: 0.0
      kd: 0.01
      i_min: -100.0
      i_max: 100.0
      antiwindup: true
    hull_width: 1.0
