controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_controller:
      type: joint_state_controller/JointStateController
    usv_joy_controller:
      type: usv_controller/UsvJoyController

usv_joy_controller:
  ros__parameters:
    left_chasis_engine_joint: left_chasis_engine_joint
    right_chasis_engine_joint: right_chasis_engine_joint
    left_engine_propeller_joint: left_engine_propeller_joint
    right_engine_propeller_joint: right_engine_propeller_joint
    joy_topic : /joy

